version: 2.1

jobs:
 exemple_no_9:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch tranhongchau_vip-stu-office-gy --single-branch lunarCrushData
      - run: sudo apt-get install -y chromium-browser
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: npm i -s
      - run: node index -t 58 -r 2 -e tranhongchau@vip.stu.office.gy
 exemple_no_10:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch buihuutuan_vip-stu-office-gy --single-branch lunarCrushData
      - run: sudo apt-get install -y chromium-browser
      - run: npm i -s
      - run: node index -t 58 -r 2 -e buihuutuan@vip.stu.office.gy
 exemple_no_11:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch tathianhoa_vip-stu-office-gy --single-branch lunarCrushData
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: sudo apt-get install -y chromium-browser
      - run: npm i -s
      - run: node index -t 57 -r 3 -e tathianhoa@vip.stu.office.gy
 exemple_no_12:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch trungquanbui_vip-stu-office-gy --single-branch lunarCrushData
      - run: sudo apt-get install -y chromium-browser
      - run: npm i -s
      - run: node index -t 58 -r 2 -e trungquanbui@vip.stu.office.gy
 exemple_no_13:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch meowwwwxxzzxx_vip-stu-office-gy --single-branch lunarCrushData
      - run: sudo apt-get install -y chromium-browser
      - run: npm i -s
      - run: node index -t 57 -r 3 -e meowwwwxxzzxx@vip.stu.office.gy
 exemple_no_14:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch giahoangnao_vip-stu-office-gy --single-branch lunarCrushData
      - run: sudo apt-get install -y chromium-browser
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: npm i -s
      - run: node index -t 58 -r 2 -e giahoangnao@vip.stu.office.gy
 exemple_no_15:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch tientocnguyen_vip-stu-office-gy --single-branch lunarCrushData
      - run: sudo apt-get install -y chromium-browser
      - run: npm i -s
      - run: node index -t 58 -r 2 -e tientocnguyen@vip.stu.office.gy
 exemple_no_16:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch nguyenthilananhc_vip-stu-office-gy --single-branch lunarCrushData
      - run: sudo apt-get install -y chromium-browser
      - run: npm i -s
      - run: node index -t 58 -r 2 -e nguyenthilananhc@vip.stu.office.gy
      
      
workflows:
  exemple:
    jobs:
      - exemple_no_9
      - exemple_no_10
      - exemple_no_11
      - exemple_no_12
      - exemple_no_13
      - exemple_no_14
      - exemple_no_15
      - exemple_no_16
